package hr.pojo;

import java.sql.Timestamp;

/**
 * EngageResumeId entity. @author MyEclipse Persistence Tools
 */

public class EngageResume implements java.io.Serializable {


	 private Integer resId;

	    /** humanName */
	    private String humanName;

	    /** engageType */
	    private String engageType;

	    /** humanAddress */
	    private String humanAddress;

	    /** humanPostcode */
	    private String humanPostcode;

	    /** humanMajorKindId */
	    private String humanMajorKindId;

	    /** humanMajorKindName */
	    private String humanMajorKindName;

	    /** humanMajorId */
	    private String humanMajorId;

	    /** humanMajorName */
	    private String humanMajorName;

	    /** humanTelephone */
	    private String humanTelephone;

	    /** humanHomephone */
	    private String humanHomephone;

	    /** humanMobilephone */
	    private String humanMobilephone;

	    /** humanEmail */
	    private String humanEmail;

	    /** humanHobby */
	    private String humanHobby;

	    /** humanSpecility */
	    private String humanSpecility;

	    /** humanSex */
	    private String humanSex;

	    /** humanReligion */
	    private String humanReligion;

	    /** humanParty */
	    private String humanParty;

	    /** humanNationality */
	    private String humanNationality;

	    /** humanBirthday */
	    private String humanBirthday;

	    /** humanAge */
	    private Integer humanAge;

	    /** humanEducatedDegree */
	    private String humanEducatedDegree;

	    /** humanEducatedYears */
	    private Integer humanEducatedYears;

	    /** humanEducatedMajor */
	    private String humanEducatedMajor;

	    /** humanCollege */
	    private String humanCollege;

	    /** humanIdcard */
	    private String humanIdcard;

	    /** humanBirthplace */
	    private String humanBirthplace;

	    /** demandSalaryStandard */
	    private Double demandSalaryStandard;

	    /** humanHistoryRecords */
	    private String humanHistoryRecords;

	    /** remark */
	    private String remark;

	    /** recomandation */
	    private String recomandation;

	    /** humanPicture */
	    private String humanPicture;

	    /** attachmentName */
	    private String attachmentName;

	    /** checkStatus */
	    private Integer checkStatus;

	    /** register */
	    private String register;

	    /** registTime */
	    private Timestamp registTime;

	    /** checker */
	    private String checker;

	    /** checkTime */
	    private Timestamp checkTime;

	    /** interviewStatus */
	    private Integer interviewStatus;

	    /** amount */
	    private Integer amount;

	    public Integer getAmount() {
			return amount;
		}

		public void setAmount(Integer amount) {
			this.amount = amount;
		}

		/** testAmount */
	    private Integer testAmount;
	    /** testChecker */
	    private String testChecker;

	    /** testCheckTime */
	    private Timestamp testCheckTime;

	    /** passRegister */
	    private String passRegister;

	    /** passRegistTime */
	    private Timestamp passRegistTime;

	    /** passChecker */
	    private String passChecker;

	    /** passCheckTime */
	    private Timestamp passCheckTime;

	    /** passCheckStatus */
	    private Integer passCheckStatus;

	    /** passCheckcomment */
	    private String passCheckcomment;

	    /** passPasscomment */
	    private String passPasscomment;

	    /** humanRace */
	    private String humanRace;

	    /** totalPoints */
	    private Double totalPoints;

	    /* This code was generated by TableGo tools, mark 1 end. */

	    /* This code was generated by TableGo tools, mark 2 begin. */

	    /**
	     * 获取resId
	     * 
	     * @return resId
	     */
	    public Integer getResId() {
	        return this.resId;
	    }

	    /**
	     * 设置resId
	     * 
	     * @param resId
	     */
	    public void setResId(Integer resId) {
	        this.resId = resId;
	    }

	    /**
	     * 获取humanName
	     * 
	     * @return humanName
	     */
	    public String getHumanName() {
	        return this.humanName;
	    }

	    /**
	     * 设置humanName
	     * 
	     * @param humanName
	     */
	    public void setHumanName(String humanName) {
	        this.humanName = humanName;
	    }

	    /**
	     * 获取engageType
	     * 
	     * @return engageType
	     */
	    public String getEngageType() {
	        return this.engageType;
	    }

	    /**
	     * 设置engageType
	     * 
	     * @param engageType
	     */
	    public void setEngageType(String engageType) {
	        this.engageType = engageType;
	    }

	    /**
	     * 获取humanAddress
	     * 
	     * @return humanAddress
	     */
	    public String getHumanAddress() {
	        return this.humanAddress;
	    }

	    /**
	     * 设置humanAddress
	     * 
	     * @param humanAddress
	     */
	    public void setHumanAddress(String humanAddress) {
	        this.humanAddress = humanAddress;
	    }

	    /**
	     * 获取humanPostcode
	     * 
	     * @return humanPostcode
	     */
	    public String getHumanPostcode() {
	        return this.humanPostcode;
	    }

	    /**
	     * 设置humanPostcode
	     * 
	     * @param humanPostcode
	     */
	    public void setHumanPostcode(String humanPostcode) {
	        this.humanPostcode = humanPostcode;
	    }

	    /**
	     * 获取humanMajorKindId
	     * 
	     * @return humanMajorKindId
	     */
	    public String getHumanMajorKindId() {
	        return this.humanMajorKindId;
	    }

	    /**
	     * 设置humanMajorKindId
	     * 
	     * @param humanMajorKindId
	     */
	    public void setHumanMajorKindId(String humanMajorKindId) {
	        this.humanMajorKindId = humanMajorKindId;
	    }

	    /**
	     * 获取humanMajorKindName
	     * 
	     * @return humanMajorKindName
	     */
	    public String getHumanMajorKindName() {
	        return this.humanMajorKindName;
	    }

	    /**
	     * 设置humanMajorKindName
	     * 
	     * @param humanMajorKindName
	     */
	    public void setHumanMajorKindName(String humanMajorKindName) {
	        this.humanMajorKindName = humanMajorKindName;
	    }

	    /**
	     * 获取humanMajorId
	     * 
	     * @return humanMajorId
	     */
	    public String getHumanMajorId() {
	        return this.humanMajorId;
	    }

	    /**
	     * 设置humanMajorId
	     * 
	     * @param humanMajorId
	     */
	    public void setHumanMajorId(String humanMajorId) {
	        this.humanMajorId = humanMajorId;
	    }

	    /**
	     * 获取humanMajorName
	     * 
	     * @return humanMajorName
	     */
	    public String getHumanMajorName() {
	        return this.humanMajorName;
	    }

	    /**
	     * 设置humanMajorName
	     * 
	     * @param humanMajorName
	     */
	    public void setHumanMajorName(String humanMajorName) {
	        this.humanMajorName = humanMajorName;
	    }

	    /**
	     * 获取humanTelephone
	     * 
	     * @return humanTelephone
	     */
	    public String getHumanTelephone() {
	        return this.humanTelephone;
	    }

	    /**
	     * 设置humanTelephone
	     * 
	     * @param humanTelephone
	     */
	    public void setHumanTelephone(String humanTelephone) {
	        this.humanTelephone = humanTelephone;
	    }

	    /**
	     * 获取humanHomephone
	     * 
	     * @return humanHomephone
	     */
	    public String getHumanHomephone() {
	        return this.humanHomephone;
	    }

	    /**
	     * 设置humanHomephone
	     * 
	     * @param humanHomephone
	     */
	    public void setHumanHomephone(String humanHomephone) {
	        this.humanHomephone = humanHomephone;
	    }

	    /**
	     * 获取humanMobilephone
	     * 
	     * @return humanMobilephone
	     */
	    public String getHumanMobilephone() {
	        return this.humanMobilephone;
	    }

	    /**
	     * 设置humanMobilephone
	     * 
	     * @param humanMobilephone
	     */
	    public void setHumanMobilephone(String humanMobilephone) {
	        this.humanMobilephone = humanMobilephone;
	    }

	    /**
	     * 获取humanEmail
	     * 
	     * @return humanEmail
	     */
	    public String getHumanEmail() {
	        return this.humanEmail;
	    }

	    /**
	     * 设置humanEmail
	     * 
	     * @param humanEmail
	     */
	    public void setHumanEmail(String humanEmail) {
	        this.humanEmail = humanEmail;
	    }

	    /**
	     * 获取humanHobby
	     * 
	     * @return humanHobby
	     */
	    public String getHumanHobby() {
	        return this.humanHobby;
	    }

	    /**
	     * 设置humanHobby
	     * 
	     * @param humanHobby
	     */
	    public void setHumanHobby(String humanHobby) {
	        this.humanHobby = humanHobby;
	    }

	    /**
	     * 获取humanSpecility
	     * 
	     * @return humanSpecility
	     */
	    public String getHumanSpecility() {
	        return this.humanSpecility;
	    }

	    /**
	     * 设置humanSpecility
	     * 
	     * @param humanSpecility
	     */
	    public void setHumanSpecility(String humanSpecility) {
	        this.humanSpecility = humanSpecility;
	    }

	    /**
	     * 获取humanSex
	     * 
	     * @return humanSex
	     */
	    public String getHumanSex() {
	        return this.humanSex;
	    }

	    /**
	     * 设置humanSex
	     * 
	     * @param humanSex
	     */
	    public void setHumanSex(String humanSex) {
	        this.humanSex = humanSex;
	    }

	    /**
	     * 获取humanReligion
	     * 
	     * @return humanReligion
	     */
	    public String getHumanReligion() {
	        return this.humanReligion;
	    }

	    /**
	     * 设置humanReligion
	     * 
	     * @param humanReligion
	     */
	    public void setHumanReligion(String humanReligion) {
	        this.humanReligion = humanReligion;
	    }

	    /**
	     * 获取humanParty
	     * 
	     * @return humanParty
	     */
	    public String getHumanParty() {
	        return this.humanParty;
	    }

	    /**
	     * 设置humanParty
	     * 
	     * @param humanParty
	     */
	    public void setHumanParty(String humanParty) {
	        this.humanParty = humanParty;
	    }

	    /**
	     * 获取humanNationality
	     * 
	     * @return humanNationality
	     */
	    public String getHumanNationality() {
	        return this.humanNationality;
	    }

	    /**
	     * 设置humanNationality
	     * 
	     * @param humanNationality
	     */
	    public void setHumanNationality(String humanNationality) {
	        this.humanNationality = humanNationality;
	    }

	    /**
	     * 获取humanBirthday
	     * 
	     * @return humanBirthday
	     */
	    public String getHumanBirthday() {
	        return this.humanBirthday;
	    }

	    /**
	     * 设置humanBirthday
	     * 
	     * @param humanBirthday
	     */
	    public void setHumanBirthday(String humanBirthday) {
	        this.humanBirthday = humanBirthday;
	    }

	    /**
	     * 获取humanAge
	     * 
	     * @return humanAge
	     */
	    public Integer getHumanAge() {
	        return this.humanAge;
	    }

	    /**
	     * 设置humanAge
	     * 
	     * @param humanAge
	     */
	    public void setHumanAge(Integer humanAge) {
	        this.humanAge = humanAge;
	    }

	    /**
	     * 获取humanEducatedDegree
	     * 
	     * @return humanEducatedDegree
	     */
	    public String getHumanEducatedDegree() {
	        return this.humanEducatedDegree;
	    }

	    /**
	     * 设置humanEducatedDegree
	     * 
	     * @param humanEducatedDegree
	     */
	    public void setHumanEducatedDegree(String humanEducatedDegree) {
	        this.humanEducatedDegree = humanEducatedDegree;
	    }

	    /**
	     * 获取humanEducatedYears
	     * 
	     * @return humanEducatedYears
	     */
	    public Integer getHumanEducatedYears() {
	        return this.humanEducatedYears;
	    }

	    /**
	     * 设置humanEducatedYears
	     * 
	     * @param humanEducatedYears
	     */
	    public void setHumanEducatedYears(Integer humanEducatedYears) {
	        this.humanEducatedYears = humanEducatedYears;
	    }

	    /**
	     * 获取humanEducatedMajor
	     * 
	     * @return humanEducatedMajor
	     */
	    public String getHumanEducatedMajor() {
	        return this.humanEducatedMajor;
	    }

	    /**
	     * 设置humanEducatedMajor
	     * 
	     * @param humanEducatedMajor
	     */
	    public void setHumanEducatedMajor(String humanEducatedMajor) {
	        this.humanEducatedMajor = humanEducatedMajor;
	    }

	    /**
	     * 获取humanCollege
	     * 
	     * @return humanCollege
	     */
	    public String getHumanCollege() {
	        return this.humanCollege;
	    }

	    /**
	     * 设置humanCollege
	     * 
	     * @param humanCollege
	     */
	    public void setHumanCollege(String humanCollege) {
	        this.humanCollege = humanCollege;
	    }

	    /**
	     * 获取humanIdcard
	     * 
	     * @return humanIdcard
	     */
	    public String getHumanIdcard() {
	        return this.humanIdcard;
	    }

	    /**
	     * 设置humanIdcard
	     * 
	     * @param humanIdcard
	     */
	    public void setHumanIdcard(String humanIdcard) {
	        this.humanIdcard = humanIdcard;
	    }

	    /**
	     * 获取humanBirthplace
	     * 
	     * @return humanBirthplace
	     */
	    public String getHumanBirthplace() {
	        return this.humanBirthplace;
	    }

	    /**
	     * 设置humanBirthplace
	     * 
	     * @param humanBirthplace
	     */
	    public void setHumanBirthplace(String humanBirthplace) {
	        this.humanBirthplace = humanBirthplace;
	    }

	    /**
	     * 获取demandSalaryStandard
	     * 
	     * @return demandSalaryStandard
	     */
	    public Double getDemandSalaryStandard() {
	        return this.demandSalaryStandard;
	    }

	    /**
	     * 设置demandSalaryStandard
	     * 
	     * @param demandSalaryStandard
	     */
	    public void setDemandSalaryStandard(Double demandSalaryStandard) {
	        this.demandSalaryStandard = demandSalaryStandard;
	    }

	    /**
	     * 获取humanHistoryRecords
	     * 
	     * @return humanHistoryRecords
	     */
	    public String getHumanHistoryRecords() {
	        return this.humanHistoryRecords;
	    }

	    /**
	     * 设置humanHistoryRecords
	     * 
	     * @param humanHistoryRecords
	     */
	    public void setHumanHistoryRecords(String humanHistoryRecords) {
	        this.humanHistoryRecords = humanHistoryRecords;
	    }

	    /**
	     * 获取remark
	     * 
	     * @return remark
	     */
	    public String getRemark() {
	        return this.remark;
	    }

	    /**
	     * 设置remark
	     * 
	     * @param remark
	     */
	    public void setRemark(String remark) {
	        this.remark = remark;
	    }

	    /**
	     * 获取recomandation
	     * 
	     * @return recomandation
	     */
	    public String getRecomandation() {
	        return this.recomandation;
	    }

	    /**
	     * 设置recomandation
	     * 
	     * @param recomandation
	     */
	    public void setRecomandation(String recomandation) {
	        this.recomandation = recomandation;
	    }

	    /**
	     * 获取humanPicture
	     * 
	     * @return humanPicture
	     */
	    public String getHumanPicture() {
	        return this.humanPicture;
	    }

	    /**
	     * 设置humanPicture
	     * 
	     * @param humanPicture
	     */
	    public void setHumanPicture(String humanPicture) {
	        this.humanPicture = humanPicture;
	    }

	    /**
	     * 获取attachmentName
	     * 
	     * @return attachmentName
	     */
	    public String getAttachmentName() {
	        return this.attachmentName;
	    }

	    /**
	     * 设置attachmentName
	     * 
	     * @param attachmentName
	     */
	    public void setAttachmentName(String attachmentName) {
	        this.attachmentName = attachmentName;
	    }

	    /**
	     * 获取checkStatus
	     * 
	     * @return checkStatus
	     */
	    public Integer getCheckStatus() {
	        return this.checkStatus;
	    }

	    /**
	     * 设置checkStatus
	     * 
	     * @param checkStatus
	     */
	    public void setCheckStatus(Integer checkStatus) {
	        this.checkStatus = checkStatus;
	    }

	    /**
	     * 获取register
	     * 
	     * @return register
	     */
	    public String getRegister() {
	        return this.register;
	    }

	    /**
	     * 设置register
	     * 
	     * @param register
	     */
	    public void setRegister(String register) {
	        this.register = register;
	    }

	    /**
	     * 获取registTime
	     * 
	     * @return registTime
	     */
	    public Timestamp getRegistTime() {
	        return this.registTime;
	    }

	    /**
	     * 设置registTime
	     * 
	     * @param registTime
	     */
	    public void setRegistTime(Timestamp registTime) {
	        this.registTime = registTime;
	    }

	    /**
	     * 获取checker
	     * 
	     * @return checker
	     */
	    public String getChecker() {
	        return this.checker;
	    }

	    /**
	     * 设置checker
	     * 
	     * @param checker
	     */
	    public void setChecker(String checker) {
	        this.checker = checker;
	    }

	    /**
	     * 获取checkTime
	     * 
	     * @return checkTime
	     */
	    public Timestamp getCheckTime() {
	        return this.checkTime;
	    }

	    /**
	     * 设置checkTime
	     * 
	     * @param checkTime
	     */
	    public void setCheckTime(Timestamp checkTime) {
	        this.checkTime = checkTime;
	    }

	    /**
	     * 获取interviewStatus
	     * 
	     * @return interviewStatus
	     */
	    public Integer getInterviewStatus() {
	        return this.interviewStatus;
	    }

	    /**
	     * 设置interviewStatus
	     * 
	     * @param interviewStatus
	     */
	    public void setInterviewStatus(Integer interviewStatus) {
	        this.interviewStatus = interviewStatus;
	    }

	    /**
	     * 获取testAmount
	     * 
	     * @return testAmount
	     */
	    public Integer getTestAmount() {
	        return this.testAmount;
	    }

	    /**
	     * 设置testAmount
	     * 
	     * @param testAmount
	     */
	    public void setTestAmount(Integer testAmount) {
	        this.testAmount = testAmount;
	    }

	    /**
	     * 获取testChecker
	     * 
	     * @return testChecker
	     */
	    public String getTestChecker() {
	        return this.testChecker;
	    }

	    /**
	     * 设置testChecker
	     * 
	     * @param testChecker
	     */
	    public void setTestChecker(String testChecker) {
	        this.testChecker = testChecker;
	    }

	    /**
	     * 获取testCheckTime
	     * 
	     * @return testCheckTime
	     */
	    public Timestamp getTestCheckTime() {
	        return this.testCheckTime;
	    }

	    /**
	     * 设置testCheckTime
	     * 
	     * @param testCheckTime
	     */
	    public void setTestCheckTime(Timestamp testCheckTime) {
	        this.testCheckTime = testCheckTime;
	    }

	    /**
	     * 获取passRegister
	     * 
	     * @return passRegister
	     */
	    public String getPassRegister() {
	        return this.passRegister;
	    }

	    /**
	     * 设置passRegister
	     * 
	     * @param passRegister
	     */
	    public void setPassRegister(String passRegister) {
	        this.passRegister = passRegister;
	    }

	    /**
	     * 获取passRegistTime
	     * 
	     * @return passRegistTime
	     */
	    public Timestamp getPassRegistTime() {
	        return this.passRegistTime;
	    }

	    /**
	     * 设置passRegistTime
	     * 
	     * @param passRegistTime
	     */
	    public void setPassRegistTime(Timestamp passRegistTime) {
	        this.passRegistTime = passRegistTime;
	    }

	    /**
	     * 获取passChecker
	     * 
	     * @return passChecker
	     */
	    public String getPassChecker() {
	        return this.passChecker;
	    }

	    /**
	     * 设置passChecker
	     * 
	     * @param passChecker
	     */
	    public void setPassChecker(String passChecker) {
	        this.passChecker = passChecker;
	    }

	    /**
	     * 获取passCheckTime
	     * 
	     * @return passCheckTime
	     */
	    public Timestamp getPassCheckTime() {
	        return this.passCheckTime;
	    }

	    /**
	     * 设置passCheckTime
	     * 
	     * @param passCheckTime
	     */
	    public void setPassCheckTime(Timestamp passCheckTime) {
	        this.passCheckTime = passCheckTime;
	    }

	    /**
	     * 获取passCheckStatus
	     * 
	     * @return passCheckStatus
	     */
	    public Integer getPassCheckStatus() {
	        return this.passCheckStatus;
	    }

	    /**
	     * 设置passCheckStatus
	     * 
	     * @param passCheckStatus
	     */
	    public void setPassCheckStatus(Integer passCheckStatus) {
	        this.passCheckStatus = passCheckStatus;
	    }

	    /**
	     * 获取passCheckcomment
	     * 
	     * @return passCheckcomment
	     */
	    public String getPassCheckcomment() {
	        return this.passCheckcomment;
	    }

	    /**
	     * 设置passCheckcomment
	     * 
	     * @param passCheckcomment
	     */
	    public void setPassCheckcomment(String passCheckcomment) {
	        this.passCheckcomment = passCheckcomment;
	    }

	    /**
	     * 获取passPasscomment
	     * 
	     * @return passPasscomment
	     */
	    public String getPassPasscomment() {
	        return this.passPasscomment;
	    }

	    /**
	     * 设置passPasscomment
	     * 
	     * @param passPasscomment
	     */
	    public void setPassPasscomment(String passPasscomment) {
	        this.passPasscomment = passPasscomment;
	    }

	    /**
	     * 获取humanRace
	     * 
	     * @return humanRace
	     */
	    public String getHumanRace() {
	        return this.humanRace;
	    }

	    /**
	     * 设置humanRace
	     * 
	     * @param humanRace
	     */
	    public void setHumanRace(String humanRace) {
	        this.humanRace = humanRace;
	    }

	    /**
	     * 获取totalPoints
	     * 
	     * @return totalPoints
	     */
	    public Double getTotalPoints() {
	        return this.totalPoints;
	    }

	    /**
	     * 设置totalPoints
	     * 
	     * @param totalPoints
	     */
	    public void setTotalPoints(Double totalPoints) {
	        this.totalPoints = totalPoints;
	    }

		@Override
		public String toString() {
			return "EngageResume [resId=" + resId + ", humanName=" + humanName + ", engageType=" + engageType
					+ ", humanAddress=" + humanAddress + ", humanPostcode=" + humanPostcode + ", humanMajorKindId="
					+ humanMajorKindId + ", humanMajorKindName=" + humanMajorKindName + ", humanMajorId=" + humanMajorId
					+ ", humanMajorName=" + humanMajorName + ", humanTelephone=" + humanTelephone + ", humanHomephone="
					+ humanHomephone + ", humanMobilephone=" + humanMobilephone + ", humanEmail=" + humanEmail
					+ ", humanHobby=" + humanHobby + ", humanSpecility=" + humanSpecility + ", humanSex=" + humanSex
					+ ", humanReligion=" + humanReligion + ", humanParty=" + humanParty + ", humanNationality="
					+ humanNationality + ", humanBirthday=" + humanBirthday + ", humanAge=" + humanAge
					+ ", humanEducatedDegree=" + humanEducatedDegree + ", humanEducatedYears=" + humanEducatedYears
					+ ", humanEducatedMajor=" + humanEducatedMajor + ", humanCollege=" + humanCollege + ", humanIdcard="
					+ humanIdcard + ", humanBirthplace=" + humanBirthplace + ", demandSalaryStandard="
					+ demandSalaryStandard + ", humanHistoryRecords=" + humanHistoryRecords + ", remark=" + remark
					+ ", recomandation=" + recomandation + ", humanPicture=" + humanPicture + ", attachmentName="
					+ attachmentName + ", checkStatus=" + checkStatus + ", register=" + register + ", registTime="
					+ registTime + ", checker=" + checker + ", checkTime=" + checkTime + ", interviewStatus="
					+ interviewStatus + ", amount=" + amount + ", testAmount=" + testAmount + ", testChecker="
					+ testChecker + ", testCheckTime=" + testCheckTime + ", passRegister=" + passRegister
					+ ", passRegistTime=" + passRegistTime + ", passChecker=" + passChecker + ", passCheckTime="
					+ passCheckTime + ", passCheckStatus=" + passCheckStatus + ", passCheckcomment=" + passCheckcomment
					+ ", passPasscomment=" + passPasscomment + ", humanRace=" + humanRace + ", totalPoints="
					+ totalPoints + "]";
		}


   
}